### ISSUE TITLE
Hi question regarding your huggingface question https://discuss.huggingface.co/t/how-to-generate-a-sequence-using-inputs-embeds-instead-of-input-ids/4145

### ISSUE THREAD

**Issue by JustABiologist** [xlpczv/Semi_Siamese#1]
Hi,

I was wondering if you ever found an answer to your question posted in the link. Very random I know, but I literially have the same problem. 

Best,
Florian

**Comment by xlpczv** [comment]
Hello,

I would say the answer was unfortunately no.
I went deep inside the transformers (bert) codes and edited them to receive my embedding inputs.

Best,
Euna

**Comment by JustABiologist** [comment]
Yo did the same thing, but slightly smarter thought about it for a few weeks and built my own sampling script lol. Hope you had success with your use case!
