### ISSUE TITLE
models problem

### ISSUE THREAD

**Issue by tangjiawei777** [xlpczv/Semi_Siamese#3]
where is the models?

**Comment by xlpczv** [comment]
Hello,
What do you mean by models?

**Comment by tangjiawei777** [comment]
when I run the prefix_tuning,it remind me no such file ../model/p0twinbert.So,I want to know where is the model

**Comment by xlpczv** [comment]
If you train the model using prefix-tuning, the model weights are saved.
p0twinbert is the model name we used for Siamese twinbert model.

In summary, you can train the model using prefix-tuning or LoRA and use the directory name you used for testing.

**Comment by tangjiawei777** [comment]
Q1：what is the mean about the full.test.run everyone column？
eg:    108939 Q0 D388799 1 -4.80563 IndriQueryLikelihood
Q2:   Can you tell me the reason why Why divide it into five parts?

**Comment by tangjiawei777** [comment]
Another question is how many column about full.train.pairs?

**Comment by tangjiawei777** [comment]
can you share the util.py about how to devided the full.train.pairs?

**Comment by tangjiawei777** [comment]
when I turn into the prefix_tuning directory,according to bash run.sh it remind me:
run.sh: line 75: models/wt_p0twinbert_f4Ps0Hs256Hl10init41lr0.0001/eval.result: No such file or directory

when I turn into the LoRA directory,according to bash run.sh it remind me:
run.sh: line 75: models/robust_twinbert_f5Ldi16La32Ldr0.1init41lr0.0001/eval.result: No such file or directory

when I turn into the fine_tuning directory,according to bash run.sh it remind me:
run.sh: line 70: models/msmarco_twinbert_fullinit41bert_lr0.00001nblr0.0001/eval.result: No such file or directory

so ,Is it mean we loss the directory of models and loss those already had been trained models like wt_p0twinbert_f4Ps0Hs256Hl10init41lr0.0001,robust_twinbert_f5Ldi16La32Ldr0.1init41lr0.0001,msmarco_twinbert_fullinit41bert_lr0.00001nblr0.0001 and so on?

**Comment by xlpczv** [comment]
If you run rerank.py and save the test results in test.run, the line 75 will be run.
The line 75 is measuring re-ranking performance metrics such as precision and nDCG based on the document scores for queries.
