### ISSUE TITLE
Datasets Problem

### ISSUE THREAD

**Issue by tangjiawei777** [xlpczv/Semi_Siamese#4]
Q1：what is the mean about the full.test.run everyone column？
eg: 1108939 Q0 D388799 1 -4.80563 IndriQueryLikelihood
eg: 1108939 Q0 D290852 2 -4.98713 IndriQueryLikelihood
eg:1108939 Q0 D2449334 3 -4.9901 IndriQueryLikelihood
eg:1108939 Q0 D884740 4 -5.03263 IndriQueryLikelihood
eg:1108939 Q0 D2449337 5 -5.03325 IndriQueryLikelihood
Q2: Can you tell me the reason why Why divide it into five parts?
like f1.test.run,f2.test.run,f3.test.run,f4.test.run,f5.test.run
Q3:how many column about full.train.pairs?
Q4:can you share the util.py about how to devided the full.train.pairs?

**Comment by xlpczv** [comment]
A1.
Each line of test.run describes query id, corresponding document id, and relevance score between them.
You can compute re-ranking metrics based on test.run.

A2.
For cross-validation, we used the five-fold data.
We followed "Parameters Learned in the Comparison of Retrieval Models using Term Dependencies" for dividing folds.

A3.
There are six columns (query id, query, positive document id, pos_doc, negative document id, neg_doc) in full.train.pairs.

A4.
If you let me know your email address, we will send the util.py later.

**Comment by Haoxiang-WasedaU** [comment]
hello, when I use the datasets you provided on google drive for reproducing, I found it lacks documents files, however, in your run.sh file, it requires providing the path, could you please tell me where can I obtain it?
Thanks a lot!

**Comment by tangjiawei777** [comment]
I am not author,you can ask the author for help&nbsp;


不忘初心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xlpczv/Semi_Siamese] Datasets Problem (Issue #4)





 
hello, when I use the datasets you provided on google drive for reproducing, I found it lacks documents files, however, in your run.sh file, it requires providing the path, could you please tell me where can I obtain it?
 Thanks a lot!

**Comment by Haoxiang-WasedaU** [comment]
> A1. Each line of test.run describes query id, corresponding document id, and relevance score between them. You can compute re-ranking metrics based on test.run.
> 
> A2. For cross-validation, we used the five-fold data. We followed "Parameters Learned in the Comparison of Retrieval Models using Term Dependencies" for dividing folds.
> 
> A3. There are six columns (query id, query, positive document id, pos_doc, negative document id, neg_doc) in full.train.pairs.
> 
> A4. If you let me know your email address, we will send the util.py later.
Hello, when I used the datasets you provided on google drive for reproducing, I found it lacks documents files. However, in your run.sh file, it requires providing the path. Could you please tell me where I can obtain it?
Thanks a lot!

**Comment by xlpczv** [comment]
Unfortunately, we cannot provide the document files due to the copyright issue (for Robust04 and ClueWeb09b) or the size of files (for MS-MARCO). You have to buy or search for the documents online. Please refer to the information for the datasets we provided in the paper.
